/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Resource = {
  _type: "resource";
  type?: "github" | "docs" | "article" | "tool" | "download" | "link";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: string;
  isFreePreview?: boolean;
  studentCount?: number;
  keyPoints?: Array<string>;
  proTip?: string;
  notes?: BlockContent;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "Beginner" | "Intermediate" | "Advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  instructor?: InstructorReference;
  category?: CategoryReference;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: ALL_COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(title asc) {    _id,    _type,    title,    slug,    summary,    coverImage,    level,    price,    popular,    studentCount,    instructor->{      _id,      name,      slug,      photo,      expertise    },    category->{      _id,      title,      slug    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[])  }
export type ALL_COURSES_QUERY_RESULT = Array<{
  _id: string;
  _type: "course";
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    expertise: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: POPULAR_COURSES_QUERY
// Query: *[_type == "course" && popular == true && defined(slug.current)] | order(title asc) [0...6] {    _id,    _type,    title,    slug,    summary,    coverImage,    level,    price,    popular,    studentCount,    instructor->{      _id,      name,      slug,      photo,      expertise    },    category->{      _id,      title,      slug    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[])  }
export type POPULAR_COURSES_QUERY_RESULT = Array<{
  _id: string;
  _type: "course";
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    expertise: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    _type,    title,    slug,    summary,    coverImage,    level,    price,    popular,    studentCount,    instructor->{      _id,      name,      slug,      photo,      expertise,      bio    },    category->{      _id,      title,      slug,      description    },    learningOutcomes[]{      _key,      icon,      title,      description    },    modules[]{      _key,      title,      summary,      lessons[]->{        _id,        _type,        title,        slug,        duration,        isFreePreview      }    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[])  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "course";
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    expertise: string | null;
    bio: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
  } | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      _type: "lesson";
      title: string | null;
      slug: Slug | null;
      duration: string | null;
      isFreePreview: boolean | null;
    }> | null;
  }> | null;
  moduleCount: number | null;
  lessonCount: number | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)][].slug.current
export type COURSE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    _type,    title,    slug,    videoUrl,    poster,    duration,    isFreePreview,    studentCount,    keyPoints,    proTip,    notes,    resources[]{      _key,      type,      title,      description,      url    },    "course": *[_type == "course" && references(^._id)][0] {      _id,      title,      slug,      instructor->{        _id,        name,        slug,        photo      },      modules[]{        title,        lessons[]->{          _id,          title,          slug,          duration,          isFreePreview        }      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "lesson";
  title: string | null;
  slug: Slug | null;
  videoUrl: string | null;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  duration: string | null;
  isFreePreview: boolean | null;
  studentCount: number | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  notes: BlockContent | null;
  resources: Array<{
    _key: string;
    type: "article" | "docs" | "download" | "github" | "link" | "tool" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    } | null;
    modules: Array<{
      title: string | null;
      lessons: Array<{
        _id: string;
        title: string | null;
        slug: Slug | null;
        duration: string | null;
        isFreePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)][].slug.current
export type LESSON_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    _type,    title,    slug,    description,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  title: string | null;
  slug: Slug | null;
  description: string | null;
  courseCount: number;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    _type,    title,    slug,    description,    "courses": *[_type == "course" && references(^._id)] | order(title asc) {      _id,      title,      slug,      summary,      coverImage,      level,      price,      popular,      studentCount,      instructor->{        _id,        name,        slug,        photo      },      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[])    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "category";
  title: string | null;
  slug: Slug | null;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    summary: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    level: "Advanced" | "Beginner" | "Intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: ALL_INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {    _id,    _type,    name,    slug,    photo,    expertise,    bio,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type ALL_INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  _type: "instructor";
  name: string | null;
  slug: Slug | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  expertise: string | null;
  bio: string | null;
  courseCount: number;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    _type,    name,    slug,    photo,    expertise,    bio,    "courses": *[_type == "course" && references(^._id)] | order(title asc) {      _id,      title,      slug,      summary,      coverImage,      level,      price,      popular,      studentCount,      category->{        _id,        title,        slug      },      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[])    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "instructor";
  name: string | null;
  slug: Slug | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  expertise: string | null;
  bio: string | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    summary: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    level: "Advanced" | "Beginner" | "Intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    category: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)] | order(title asc) {\n    _id,\n    _type,\n    title,\n    slug,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    instructor->{\n      _id,\n      name,\n      slug,\n      photo,\n      expertise\n    },\n    category->{\n      _id,\n      title,\n      slug\n    },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[])\n  }\n': ALL_COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && popular == true && defined(slug.current)] | order(title asc) [0...6] {\n    _id,\n    _type,\n    title,\n    slug,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    instructor->{\n      _id,\n      name,\n      slug,\n      photo,\n      expertise\n    },\n    category->{\n      _id,\n      title,\n      slug\n    },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[])\n  }\n': POPULAR_COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    slug,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    instructor->{\n      _id,\n      name,\n      slug,\n      photo,\n      expertise,\n      bio\n    },\n    category->{\n      _id,\n      title,\n      slug,\n      description\n    },\n    learningOutcomes[]{\n      _key,\n      icon,\n      title,\n      description\n    },\n    modules[]{\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        _id,\n        _type,\n        title,\n        slug,\n        duration,\n        isFreePreview\n      }\n    },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[])\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)][].slug.current\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    slug,\n    videoUrl,\n    poster,\n    duration,\n    isFreePreview,\n    studentCount,\n    keyPoints,\n    proTip,\n    notes,\n    resources[]{\n      _key,\n      type,\n      title,\n      description,\n      url\n    },\n    "course": *[_type == "course" && references(^._id)][0] {\n      _id,\n      title,\n      slug,\n      instructor->{\n        _id,\n        name,\n        slug,\n        photo\n      },\n      modules[]{\n        title,\n        lessons[]->{\n          _id,\n          title,\n          slug,\n          duration,\n          isFreePreview\n        }\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)][].slug.current\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    _type,\n    title,\n    slug,\n    description,\n    "courseCount": count(*[_type == "course" && references(^._id)])\n  }\n': ALL_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    slug,\n    description,\n    "courses": *[_type == "course" && references(^._id)] | order(title asc) {\n      _id,\n      title,\n      slug,\n      summary,\n      coverImage,\n      level,\n      price,\n      popular,\n      studentCount,\n      instructor->{\n        _id,\n        name,\n        slug,\n        photo\n      },\n      "moduleCount": count(modules),\n      "lessonCount": count(modules[].lessons[])\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)] | order(name asc) {\n    _id,\n    _type,\n    name,\n    slug,\n    photo,\n    expertise,\n    bio,\n    "courseCount": count(*[_type == "course" && references(^._id)])\n  }\n': ALL_INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    _type,\n    name,\n    slug,\n    photo,\n    expertise,\n    bio,\n    "courses": *[_type == "course" && references(^._id)] | order(title asc) {\n      _id,\n      title,\n      slug,\n      summary,\n      coverImage,\n      level,\n      price,\n      popular,\n      studentCount,\n      category->{\n        _id,\n        title,\n        slug\n      },\n      "moduleCount": count(modules),\n      "lessonCount": count(modules[].lessons[])\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
  }
}
